version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_CONFIG=development
      - DATABASE_URL=postgresql://backend_user:backend_password@db:5432/backend_test
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000 --debug
    networks:
      - backend-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=backend_test
      - POSTGRES_USER=backend_user
      - POSTGRES_PASSWORD=backend_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
